namespace GlobalRubber.MMM.Domain.Constants;

/// <summary>
/// machine_pm_transaction.schedule_type / mold_pm_transaction.schedule_type (migration 025, CK_..._schedule_type, default
/// 'Automatic'). Automatic = generated by the system: a recurring Machine PM occurrence of a PM plan, or the usage-based
/// ('Shot-based') Mold PM. Manual = ONE maintenance a user scheduled for a specific machine or mold on a specific date - it
/// has a title, no plan (checklist_id NULL), never a successor, and never takes part in the mold's usage cycle.
/// </summary>
public static class PmScheduleType
{
    public const string Automatic = "Automatic";
    public const string Manual = "Manual";

    public static readonly IReadOnlyList<string> All = new[] { Automatic, Manual };
}
